/**
 * Keyword search over the vendored Mulberry Symbols set.
 *
 * Fully offline: the index (`mulberry-index.json`, generated by
 * `scripts/build-mulberry-index.mjs` from the upstream metadata plus the
 * hand-curated Spanish list) ships with the package, so a search makes no
 * network request at all.
 *
 * Import from `@voxa/symbols/search` (server side). The main entry point does
 * not import the index, which keeps it out of browser bundles.
 */
import indexData from './mulberry-index.json' with { type: 'json' };
import { MULBERRY_ASSET_BASE } from './mulberry.js';
import type { SearchSymbolsOptions, SymbolSearchHit } from './types.js';

export type MulberryLanguage = 'es' | 'en' | 'fr';

export interface MulberryIndexEntry {
  slug: string;
  file: string;
  category: string;
  en: string[];
  es: string[];
  fr: string[];
  tags?: string[];
  /** Upstream "rated" flag (anatomical symbols): returned only on an exact keyword match. */
  rated?: boolean;
}

export interface MulberryIndexMeta {
  upstreamVersion: string;
  upstreamCommit: string;
  count: number;
  spanishCount: number;
  [key: string]: unknown;
}

const INDEX = indexData as unknown as { meta: MulberryIndexMeta; symbols: MulberryIndexEntry[] };

export const MULBERRY_INDEX_META: MulberryIndexMeta = INDEX.meta;
export const MULBERRY_INDEX: readonly MulberryIndexEntry[] = INDEX.symbols;

const LANGUAGES: readonly MulberryLanguage[] = ['es', 'en', 'fr'];

/** Lowercase, strip diacritics and punctuation, collapse whitespace. */
export function normalizeKeyword(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[¿?¡!.,;:"'()]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/** `es-MX` → `es`; unknown → `es` (Voxa's default content language). */
export function searchLanguage(locale: string | undefined): MulberryLanguage {
  const base = (locale ?? '').toLowerCase().split(/[-_]/)[0] ?? '';
  return (LANGUAGES as readonly string[]).includes(base) ? (base as MulberryLanguage) : 'es';
}

/** Requested language first, then the others in a fixed order. */
function languageOrder(primary: MulberryLanguage): MulberryLanguage[] {
  return [primary, ...LANGUAGES.filter((lang) => lang !== primary)];
}

const LANGUAGE_WEIGHT = [1, 0.8, 0.6] as const;

interface PreparedEntry {
  entry: MulberryIndexEntry;
  keywords: Record<MulberryLanguage, string[]>;
  tags: string[];
}

const PREPARED: PreparedEntry[] = MULBERRY_INDEX.map((entry) => ({
  entry,
  keywords: {
    es: entry.es.map(normalizeKeyword),
    en: entry.en.map(normalizeKeyword),
    fr: entry.fr.map(normalizeKeyword),
  },
  tags: (entry.tags ?? []).map(normalizeKeyword),
}));

/** Score of one keyword against the query; 0 when it does not match. */
function keywordScore(keyword: string, query: string): number {
  if (!keyword) return 0;
  if (keyword === query) return 100;
  const words = keyword.split(' ');
  if (words.includes(query) || keyword.startsWith(`${query} `)) return 70;
  if (keyword.startsWith(query)) return 50;
  if (query.length >= 3 && words.some((word) => word.startsWith(query))) return 40;
  if (query.length >= 3 && keyword.includes(query)) return 20;
  return 0;
}

interface Scored {
  prepared: PreparedEntry;
  score: number;
  exact: boolean;
  keyword: string;
}

function scoreEntry(prepared: PreparedEntry, query: string, order: MulberryLanguage[]): Scored | null {
  let best: Scored | null = null;
  order.forEach((lang, langIndex) => {
    const weight = LANGUAGE_WEIGHT[langIndex] ?? 0.5;
    prepared.keywords[lang].forEach((keyword, keywordIndex) => {
      const raw = keywordScore(keyword, query);
      if (raw === 0) return;
      // The first keyword is the symbol's primary label.
      const score = raw * weight + (keywordIndex === 0 ? 5 : 0);
      if (!best || score > best.score) {
        best = {
          prepared,
          score,
          exact: raw === 100,
          keyword: prepared.entry[lang][keywordIndex] ?? keyword,
        };
      }
    });
  });
  if (!best && prepared.tags.includes(query)) {
    best = { prepared, score: 15, exact: false, keyword: prepared.entry.en[0] ?? prepared.entry.slug };
  }
  return best;
}

function displayKeyword(entry: MulberryIndexEntry, lang: MulberryLanguage, matched: string): string {
  const own = entry[lang][0];
  return own ?? matched;
}

/** Web path of an index entry's SVG. */
export function mulberryIndexImageUrl(entry: Pick<MulberryIndexEntry, 'file'>): string {
  return `${MULBERRY_ASSET_BASE}/${entry.file}`;
}

/**
 * Search the vendored Mulberry set. Ranking: exact keyword in the requested
 * language, then exact in another language, then whole-word, prefix and
 * substring matches; ties go to the shorter keyword. Rated (anatomical)
 * symbols appear only for an exact keyword match.
 */
export function searchMulberryIndex(query: string, options: SearchSymbolsOptions = {}): SymbolSearchHit[] {
  const normalized = normalizeKeyword(query);
  if (normalized.length < 2) return [];

  const lang = searchLanguage(options.locale);
  const order = languageOrder(lang);
  const limit = Math.min(24, Math.max(1, Math.floor(options.limit ?? 12)));

  const scored: Scored[] = [];
  for (const prepared of PREPARED) {
    const result = scoreEntry(prepared, normalized, order);
    if (!result) continue;
    if (prepared.entry.rated && !result.exact) continue;
    scored.push(result);
  }

  scored.sort(
    (a, b) =>
      b.score - a.score ||
      a.keyword.length - b.keyword.length ||
      a.prepared.entry.slug.localeCompare(b.prepared.entry.slug),
  );

  return scored.slice(0, limit).map(({ prepared, keyword }) => ({
    id: prepared.entry.slug,
    keyword: displayKeyword(prepared.entry, lang, keyword),
    imageUrl: mulberryIndexImageUrl(prepared.entry),
    source: 'mulberry' as const,
    file: prepared.entry.file,
    category: prepared.entry.category,
    tags: prepared.entry.tags ?? [],
  }));
}

/** Look up an index entry by slug. */
export function findMulberrySymbol(slug: string): MulberryIndexEntry | undefined {
  return MULBERRY_INDEX.find((entry) => entry.slug === slug);
}
