apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voxa-staging

resources:
- namespace.yaml
- signature-policyexception.yaml
- network-policies.yaml
- voxa-api-deployment.yaml
- voxa-api-service.yaml
- voxa-web-deployment.yaml
- voxa-web-service.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: voxa
    enclii.dev/environment: staging
    enclii.dev/managed-by: switchyard

images:
- digest: sha256:fa2423bf8e3e8035ef3528b83fcd505a281feb6b99acbae22a824160f9f6dac3
  name: voxa-api
  newName: ghcr.io/madfam-org/voxa/voxa-api
- digest: sha256:e0d70e9b1b11d1ca0cf6ed764410a685179ecfca86296d3509b69dd060971572
  name: voxa-web
  newName: ghcr.io/madfam-org/voxa/voxa-web
