apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voxa-staging

resources:
- namespace.yaml
- network-policies.yaml
- pod-disruption-budgets.yaml
- signature-policyexception.yaml
- voxa-api-deployment.yaml
- voxa-api-service.yaml
- voxa-web-deployment.yaml
- voxa-web-service.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: voxa
    enclii.dev/environment: staging
    enclii.dev/managed-by: switchyard

images:
- digest: sha256:f966d6c2eb63910f72387225f555a4b3d9335389de2b5230fe131ec1dd14516f
  name: voxa-api
  newName: ghcr.io/madfam-org/voxa/voxa-api
- digest: sha256:bfc07ab3b1989786b6e6b2771390987bab43680e63f972a0ed865bf986b8f50a
  name: voxa-web
  newName: ghcr.io/madfam-org/voxa/voxa-web
