---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voxa-api
  labels:
    app: voxa-api
    app.kubernetes.io/name: voxa-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: voxa
    enclii.dev/managed-by: switchyard
    enclii.dev/environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voxa-api
  template:
    metadata:
      labels:
        app: voxa-api
        app.kubernetes.io/name: voxa-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: voxa
        enclii.dev/managed-by: switchyard
        enclii.dev/environment: staging
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: ghcr.io/madfam-org/voxa/voxa-api@sha256:71d51d97d071caf7c213702f81085554cb4937d6a55579a23dca37fc5568eeaa
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
            - name: LISTEN_HOST
              value: "0.0.0.0"
            - name: ENCLII_ENVIRONMENT
              value: staging
          envFrom:
            - secretRef:
                name: voxa-secrets
                optional: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 12
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          emptyDir: {}
