apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voxa

resources:
- namespace.yaml
- network-policies.yaml
- pod-disruption-budgets.yaml
- signature-policyexception.yaml
- voxa-api-deployment.yaml
- voxa-api-service.yaml
- voxa-web-deployment.yaml
- voxa-web-service.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: voxa
    enclii.dev/managed-by: switchyard

images:
- digest: sha256:88a5f16905e9c3d1df3e688ddadd5f4c58b7cafbe48531f266477bc1d4e3dabe
  name: voxa-api
  newName: ghcr.io/madfam-org/voxa/voxa-api
- digest: sha256:9381aa30bb151259954b2e216ed97b8d9105dd7175f06a4cad7869ebcaca9374
  name: voxa-web
  newName: ghcr.io/madfam-org/voxa/voxa-web
