apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voxa

resources:
- namespace.yaml
- network-policies.yaml
- pod-disruption-budgets.yaml
- signature-policyexception.yaml
- voxa-api-deployment.yaml
- voxa-api-service.yaml
- voxa-web-deployment.yaml
- voxa-web-session-externalsecret.yaml
- voxa-web-service.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: voxa
    enclii.dev/managed-by: switchyard

images:
- digest: sha256:e5fbcf088addd7c7f77bbf1080f6594710ff88baedf4230a84fec4fb59db84c6
  name: voxa-api
  newName: ghcr.io/madfam-org/voxa/voxa-api
- digest: sha256:6719d29d818b1338f13ef09212ef15cc28eda3a0990820369aaa8a2d85cf0d6c
  name: voxa-web
  newName: ghcr.io/madfam-org/voxa/voxa-web
