apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voxa

resources:
- namespace.yaml
- network-policies.yaml
- signature-policyexception.yaml
- voxa-api-deployment.yaml
- voxa-api-service.yaml
- voxa-web-deployment.yaml
- voxa-web-service.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: voxa
    enclii.dev/managed-by: switchyard

images:
- digest: sha256:e7b1d4e86656ece7c1924a8f9e1aed92b89e026464532a5ffa911734c1c46323
  name: voxa-api
  newName: ghcr.io/madfam-org/voxa/voxa-api
- digest: sha256:89d679eb9f2f57bc00ab41018ed883540141cd47e84f4f0b04a565926c569698
  name: voxa-web
  newName: ghcr.io/madfam-org/voxa/voxa-web
