---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voxa-web
  labels:
    app: voxa-web
    app.kubernetes.io/name: voxa-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: voxa
    enclii.dev/managed-by: switchyard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voxa-web
  template:
    metadata:
      labels:
        app: voxa-web
        app.kubernetes.io/name: voxa-web
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: voxa
        enclii.dev/managed-by: switchyard
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: ghcr.io/madfam-org/voxa/voxa-web@sha256:74752fe1899fa8e456c58f62aafdc862de2cf0ca74b6fde9373e2b57e9eddee9
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: NEXT_PUBLIC_API_URL
              value: "https://voxa-api.madfam.io"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /api/health
              port: http
            failureThreshold: 12
            periodSeconds: 5
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
