---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voxa-api
  labels:
    app: voxa-api
    app.kubernetes.io/name: voxa-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: voxa
    enclii.dev/managed-by: switchyard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voxa-api
  template:
    metadata:
      labels:
        app: voxa-api
        app.kubernetes.io/name: voxa-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: voxa
        enclii.dev/managed-by: switchyard
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: ghcr.io/madfam-org/voxa/voxa-api@sha256:0213b6cd24c7f91d16f1572d583d0310b4925bcdb93d1b7b1b22b26aa82b9663
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
            - name: LISTEN_HOST
              value: "0.0.0.0"
          envFrom:
            - secretRef:
                name: voxa-secrets
                optional: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /health/ready
              port: http
            failureThreshold: 12
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          emptyDir: {}